spring.application.name=todo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/todo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database=mysql

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.org.hibernate=DEBUG
